test diff cover install and check path

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,22 +52,28 @@ jobs:
       - name: Fetch base branch
         run: git fetch origin main
         
-      # Install diff-cover globally to access it
-      - name: Install diff-cover globally
-        run: pip install --target=/usr/local/bin diff-cover
-
-      # Compare coverage with the base branch
-      - name: Compare coverage
+      - name: Install diff-cover
         run: |
-         git checkout main
-         python -m coverage run -p -m pytest src/jp2_remediator/tests/unit
-         python -m coverage xml -o coverage-base.xml
-         git checkout -
-         ~/.local/bin/diff-cover --compare-branch=main coverage.xml
-         python diff-cover --compare-branch=main coverage.xml
+          pip install --user diff-cover
+          find $HOME -name "diff-cover" || echo "diff-cover not found"
+
+      - name: Add diff-cover to PATH
+        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
+
+      - name: Run diff-cover
+        run: diff-cover coverage.xml
+
+      # # Compare coverage with the base branch
+      # - name: Compare coverage
+      #   run: |
+      #    pip install diff-cover
+      #    git checkout main
+      #    python -m coverage run -p -m pytest src/jp2_remediator/tests/unit
+      #    python -m coverage xml -o coverage-base.xml
+      #    git checkout -
+      #    python diff-cover --compare-branch=main coverage.xml
          
-      # Fail if coverage decreases
-      - name: Fail if coverage decreases
-        run: |
-          ~/.local/bin/diff-cover --compare-branch=main coverage.xml --fail-under=100
-
+      # # Fail if coverage decreases
+      # - name: Fail if coverage decreases
+      #   run: |
+      #     python diff-cover --compare-branch=main coverage.xml --fail-under=100
