Replace print statements with logging (#4)
* Replace print statements with logging

- defaults to only console logging
- defaults to WARNING level
   - configurable with: `export APP_LOG_LEVEL=[INFO|DEBUG]`

* Merge awoods-logging into logging (#3)

* linter for box reader after logging

* comment out diff cover

remove socket

* skip processing of files where n value is not 1

* tests with 65% cvg

* add in github actions install of diff cover globally

* update paths for diff cover

* test diff cover install and check path

* uncomment diff cover test

* uncomment diff cover test 2

* new coverage test

* full test coverage

* flake8 passes all files

* check flake8 version

* mod flake8 command for 120 line length

* add additional test coverage, stops early if not 85

---------

Co-authored-by: kim pham <kimpham54@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,8 +32,9 @@ jobs:
       - name: Run flake8
         run: | 
           pip install flake8
+          flake8 --version
           # stop the build if there are flake8 errors
-          flake8 . --count --show-source --statistics
+          flake8 . --count --show-source --statistics --max-line-length 120
 
       - name: Run unit tests
         run: |
@@ -45,25 +46,26 @@ jobs:
           pip install coverage
           python -m coverage run -p -m pytest src/jp2_remediator/tests/unit
           python -m coverage combine
-          python -m coverage report -m --skip-covered
+          python -m coverage report -m --skip-covered --fail-under=85
           python -m coverage xml
       
       # Fetch base branch for comparison (e.g., main)
       - name: Fetch base branch
         run: git fetch origin main
         
-      # Compare coverage with the base branch
+      - name: Install diff-cover
+        run: |
+          pip install --user diff-cover
+          find $HOME -name "diff-cover" || echo "diff-cover not found"
+
+      - name: Add diff-cover to PATH
+        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
+
+      # Compare coverage with the base branch, if decreases fails, if under 85 percent fails
       - name: Compare coverage
         run: |
-         pip install diff-cover
          git checkout main
          python -m coverage run -p -m pytest src/jp2_remediator/tests/unit
          python -m coverage xml -o coverage-base.xml
          git checkout -
-         python diff-cover --compare-branch=main coverage.xml
-         
-      # Fail if coverage decreases
-      - name: Fail if coverage decreases
-        run: |
-          python diff-cover --compare-branch=main coverage.xml --fail-under=100
-
+         diff-cover --compare-branch=main coverage.xml --fail-under=85
